### PR TITLE
Fix typo group -> project in readme

### PR DESCRIPTION
**Pull request by stevencrake-nscale**
On reading your readme file in the projects section I've spotted it looks like you meant project here, rather than group.

### CODE REVIEW

**Review by spjmurray — APPROVED** [review]

**Comment by spjmurray** [comment]
Glad you pay more attention than I do!

**Comment by spjmurray** [comment]
Ugh, sorry @stevencrake-nscale

> The base branch requires all commits to be signed.

Get secure!

**Review by spjmurray — APPROVED** [review]

**Comment by spjmurray** [comment]
Run CI jobs you bastard!

**Comment by spjmurray** [comment]
Tableflip

**Comment by ekarcnevets** [comment]
What was the magic sauce?

**Pull request merged**
